# config.toml

[theme]
# Base theme setting
base = "light"

# Color configuration
primaryColor = "#d33682"
backgroundColor = "#002b36"
secondaryBackgroundColor = "#586e75"
textColor = "#ffffff"

[client]
toolbarMode = "minimal"
